export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';
export const IS_EDITING_ROW = 'IS_EDITING_ROW';
export const EDIT_REMINDER_TEXT = 'EDIT_REMINDER_TEXT';
export const REMINDER_DONE = 'REMINDER_DONE';
export const CLEAR_DONE_REMINDERS = 'CLEAR_DONE_REMINDERS';
export const CHANGE_CURRENT_FILTER = 'CHANGE_CURRENT_FILTER';

